version: "3"

services:
    database:
        image: 'mongo'
        container_name: 'mongodb_asyncio_chat'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=unsafe_shit

        ports:
            - '27017-27019:27017-27019'

    chat_server:
        command: cd ./app && python start.py
        ports:
            - 8080:8080
        depends_on:
            - "database"