import Quadrant.resources.session_resource.current_session
import Quadrant.resources.session_resource.session_pages
import Quadrant.resources.session_resource.exact_session
from .router import router
